aurora_home:
    path: "/api/home"
    methods: GET
    controller: App\Aurora\Http\Controller\HomeController:index

articles.get:
    path: "/api/articles"
    methods: GET
    controller: App\Aurora\Http\Controller\ArticleController:index

articles.get.by.id:
    path: "/api/article/{id}"
    methods: GET
    controller: App\Aurora\Http\Controller\ArticleController:article

articles.create:
    path: "/api/articles"
    methods: POST
    controller: App\Aurora\Http\Controller\ArticleController:create

aurora.search:
    path: "/api/search"
    methods: GET
    controller: App\Aurora\Http\Controller\SearchController:index

users.get:
    path: "/api/users"
    methods: GET
    controller: App\Aurora\Http\Controller\UserController:index

users.get.by.id:
    path: "/api/user/{id}"
    methods: GET
    controller: App\Aurora\Http\Controller\UserController:user