imports:
  - { resource: "transformers.yaml"}

services:
  ## here will be aurora's services

  aurora.event_listener.api_exception:
     class: App\Aurora\App\EventListener\ApiExceptionListener
     arguments: ['%%kernel.debug%%']
     tags:
         - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }

  aurora.fractal.manager:
       class: App\Aurora\App\Support\FractalService
       public: true
       arguments: ['%siteUrl%']
  App\Aurora\App\Support\FractalService: '@aurora.fractal.manager'

  aurora.article.service:
      class: App\Aurora\Domain\Article\ArticleService
      public: true
      arguments: ['@doctrine.orm.entity_manager','@aurora.article.transformer']
  App\Aurora\Domain\Article\ArticleService: '@aurora.article.service'

  ## make fos oauth service public
  fos_oauth_server.client_manager.default:
      class: FOS\OAuthServerBundle\Entity\ClientManager
      public: true
      arguments: ['@Doctrine\ORM\EntityManagerInterface','%fos_oauth_server.model.client.class%']

  FOS\OAuthServerBundle\Model\AccessTokenManagerInterface:
      alias: fos_oauth_server.access_token_manager.default