services:
  ## here will be aurora's services

  aurora.article.service:
      class: App\Aurora\Domain\Article\ArticleService
      arguments: ['@doctrine.orm.entity_manager']

  App\Aurora\Domain\Article\ArticleService: '@aurora.article.service'
