NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /

aurora:
    # loads routes from the YAML or XML files found in some bundle directory
    resource: '../src/Aurora/Resources/routing/'
    type:     directory

authorization:
    resource: '../src/Authorization/Controller/'
    type: annotation


### OVERRIDE DEFAULT fos oauth controller services to disable GET methods
fos_oauth_server_authorize:
    path: /oauth/v2/auth
    methods: POST
    controller: App\Authorization\Controller\OAuthAuthorizeController:authorize

fos_oauth_server_token:
    path: /oauth/v2/token
    methods: POST
    controller: App\Authorization\Controller\OAuthTokenController:tokenAction